version: '3'
services:
  traefik:
    image: traefik:v2.0.2
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_default
    ports:
      - 8888:80
      - 8443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/traefik.yml:ro
      - ./config/acme/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(alpha.`${HOST:?HOST environment varaible is required}`)&& ( PathPrefix(`/dashboard`) || PathPrefix(`/api`) )"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$2y$$05$$0M37fViQ3uHTqkNl0c9C1.disDp5hKPRhVdDetC8MNZ11VXq6msly"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(alpha.`${HOST:?HOST environment varaible is required}`) && ( PathPrefix(`/dashboard`) || PathPrefix(`/api`) )"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=http"
      - "traefik.http.routers.traefik-secure.service=api@internal"

  vue-services:
    image: nsfearthcube/ec_facets_api_nodejs:latest
    #build: ./server
    environment:
      - NODE_ENV=production
      - S3ADDRESS=s3system:9000
      - S3BUCKET=sites
      - S3PREFIX=alpha
      - DOMAIN=https://alpha.${HOST:?HOST environment varaible is required}/
      - S3KEY={EXAMPLE}
      - S3SECRET={EXAMPLEKEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alpha-server.entrypoints=http"
      - "traefik.http.routers.alpha-server.priority=90"
      - "traefik.http.routers.alpha-server.rule=Host(`alpha.${HOST:?HOST environment variable is required}`) && PATH(`/api`)"
      - "traefik.http.middlewares.alpha-server-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.alpha-server.middlewares=alpha-server-https-redirect"
      - "traefik.http.routers.alpha-server-secure.priority=91"
      - "traefik.http.routers.alpha-server-secure.entrypoints=https"
      - "traefik.http.routers.alpha-server-secure.rule=Host(`alpha.${HOST:?HOST environment is required}`) && PATH(`/api`)"
      - "traefik.http.routers.alpha-server-secure.tls=true"
      - "traefik.http.routers.alpha-server-secure.tls.certresolver=http"
      - "traefik.http.routers.alpha-server-secure.service=alpha-server"
      - "traefik.http.services.alpha-server.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.middlewares.alpha-server.headers.accesscontrolallowmethods=GET,OPTIONS,POST"
      - "traefik.http.middlewares.alpha-server.headers.accesscontrolalloworigin=*"
      - "traefik.http.middlewares.alpha-server.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.alpha-server.headers.addvaryheader=true"
      - "traefik.http.middlewares.ecapi_prefix.StripPrefix.prefixes=/ec/api"
      - "traefik.http.routers.alpha-server.middlewares=ecapi_prefix"
    networks:
      - traefik_default
  vue-client:
    image: nsfearthcube/ec_facets_client:latest
    #build: ./client
    environment:
      - NODE_ENV=production
      - DOMAIN=https://alpha.${HOST:?HOST environment varaible is required}/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alpha.entrypoints=http"
      - "traefik.http.routers.alpha.priority=10"
      - "traefik.http.routers.alpha.rule=Host(`alpha.${HOST:?HOST environment varaible is required}`)"
      - "traefik.http.middlewares.alpha-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.alpha.middlewares=alpha-https-redirect"
      - "traefik.http.routers.alpha-secure.entrypoints=https"
      - "traefik.http.routers.alpha-secure.priority=11"
      - "traefik.http.routers.alpha-secure.rule=Host(`alpha.${HOST:?HOST environment is required}`)"
      - "traefik.http.routers.alpha-secure.tls=true"
      - "traefik.http.routers.alpha-secure.tls.certresolver=http"
      - "traefik.http.routers.alpha-secure.service=alpha"
      - "traefik.http.services.alpha.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.middlewares.alpha.headers.accesscontrolallowmethods=GET,OPTIONS,POST"
      - "traefik.http.middlewares.alpha.headers.accesscontrolalloworigin=*"
      - "traefik.http.middlewares.alpha.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.alpha.headers.addvaryheader=true"
    networks:
      - traefik_default
networks:
  traefik_default:
